function makeRoom(id, name, x, y, width, height, floor = 1) {
  return {
    id,
    name,
    x,
    y,
    width,
    height,
    floor,
    layer: "ARCHITECTURE",
  };
}

function generateBlueprint(prompt) {
  const text = prompt.toLowerCase();

  if (text.includes("school")) {
    return {
      type: "blueprint-generator",
      prompt,
      rooms: [
        makeRoom("school-lobby", "Main Lobby", 35, 8, 18, 10),
        makeRoom("school-office", "Main Office", 15, 8, 16, 10),
        makeRoom("classroom-1", "Classroom 1", 10, 25, 18, 14),
        makeRoom("classroom-2", "Classroom 2", 32, 25, 18, 14),
        makeRoom("classroom-3", "Classroom 3", 54, 25, 18, 14),
        makeRoom("cafeteria", "Cafeteria", 15, 48, 26, 18),
        makeRoom("gym", "Gym", 50, 48, 28, 22),
      ],
      notes: ["School layout generated by Sentinel Nexus AI."],
    };
  }

  if (text.includes("hospital")) {
    return {
      type: "blueprint-generator",
      prompt,
      rooms: [
        makeRoom("hospital-lobby", "Main Lobby", 35, 8, 20, 12),
        makeRoom("er", "Emergency Entrance", 8, 25, 22, 16),
        makeRoom("imaging", "Imaging", 35, 25, 20, 16),
        makeRoom("patient-wing-a", "Patient Wing A", 60, 18, 25, 14),
        makeRoom("patient-wing-b", "Patient Wing B", 60, 40, 25, 14),
        makeRoom("cafeteria", "Cafeteria", 25, 50, 22, 16),
        makeRoom("offices", "Offices", 8, 50, 15, 16),
      ],
      notes: ["Hospital starter layout generated by Sentinel Nexus AI."],
    };
  }

  if (text.includes("warehouse")) {
    return {
      type: "blueprint-generator",
      prompt,
      rooms: [
        makeRoom("warehouse", "Warehouse Floor", 10, 15, 58, 42),
        makeRoom("office", "Office Area", 70, 15, 18, 16),
        makeRoom("shipping", "Shipping", 70, 35, 18, 18),
        makeRoom("storage", "Storage", 15, 60, 24, 14),
      ],
      notes: ["Warehouse layout generated by Sentinel Nexus AI."],
    };
  }

  return {
    type: "blueprint-generator",
    prompt,
    rooms: [
      makeRoom("main-building", "Main Building", 10, 10, 30, 20),
      makeRoom("office", "Office", 45, 10, 18, 14),
      makeRoom("utility", "Utility", 45, 30, 18, 12),
    ],
    notes: ["Generic layout generated by Sentinel Nexus AI."],
  };
}

module.exports = { generateBlueprint };
