const express = require("express");
const cors = require("cors");
const { z } = require("zod");

const app = express();

app.use(cors());
app.use(express.json({ limit: "10mb" }));

const gatewaySchema = z.object({
  requestType: z.string().min(1),
  prompt: z.string().optional().default(""),
  blueprint: z.any().optional(),
  project: z.any().optional(),
  projectContext: z.any().optional(),
});

function generateBlueprint(prompt) {
  const text = prompt.toLowerCase();

  if (text.includes("school")) {
    return {
      type: "blueprint-generator",
      rooms: [
        { id: "school-lobby", name: "Main Lobby", x: 35, y: 8, width: 18, height: 10, floor: 1, layer: "ARCHITECTURE" },
        { id: "classroom-1", name: "Classroom 1", x: 10, y: 25, width: 18, height: 14, floor: 1, layer: "ARCHITECTURE" },
        { id: "classroom-2", name: "Classroom 2", x: 32, y: 25, width: 18, height: 14, floor: 1, layer: "ARCHITECTURE" },
        { id: "cafeteria", name: "Cafeteria", x: 15, y: 48, width: 26, height: 18, floor: 1, layer: "ARCHITECTURE" },
        { id: "gym", name: "Gym", x: 50, y: 48, width: 28, height: 22, floor: 1, layer: "ARCHITECTURE" }
      ],
      notes: ["School layout generated by Sentinel Nexus AI."]
    };
  }

  return {
    type: "blueprint-generator",
    rooms: [
      { id: "main-building", name: "Main Building", x: 10, y: 10, width: 35, height: 25, floor: 1, layer: "ARCHITECTURE" }
    ],
    notes: ["Starter building generated by Sentinel Nexus AI."]
  };
}

function placeDevices(blueprint) {
  const rooms = blueprint?.rooms || [];

  return {
    type: "device-placement",
    devices: rooms.flatMap((room, index) => [
      {
        id: `sd-${index + 1}`,
        type: "SMOKE",
        label: "SD",
        x: room.x + room.width / 2,
        y: room.y + room.height / 2,
        size: 42,
        layer: "FIRE_ALARM",
        notes: "AI suggested smoke detector."
      },
      {
        id: `hs-${index + 1}`,
        type: "HORN_STROBE",
        label: "HS",
        x: room.x + 2,
        y: room.y + 2,
        size: 42,
        layer: "FIRE_ALARM",
        notes: "AI suggested horn/strobe."
      }
    ]),
    notes: ["Verify final fire alarm design with AHJ."]
  };
}

function estimateMaterials(blueprint) {
  const roomCount = blueprint?.rooms?.length || 1;

  return {
    type: "material-estimate",
    materials: {
      SD: roomCount,
      HS: Math.ceil(roomCount / 2),
      PS: 2,
      FACP: 1,
      CABLE_FT: roomCount * 150
    },
    notes: ["Estimate only. Field verification required."]
  };
}

app.get("/", (_req, res) => {
  res.json({
    name: "Sentinel Nexus AI",
    status: "online",
    endpoints: ["/gateway", "/ai", "/generate-building"]
  });
});

app.post("/gateway", async (req, res) => {
  try {
    const parsed = gatewaySchema.safeParse(req.body);

    if (!parsed.success) {
      return res.status(400).json({ error: "Invalid gateway request." });
    }

    const { requestType, prompt, blueprint } = parsed.data;

    if (requestType === "blueprint-generator") {
      return res.json(generateBlueprint(prompt));
    }

    if (requestType === "device-placement") {
      return res.json(placeDevices(blueprint));
    }

    if (requestType === "material-estimate") {
      return res.json(estimateMaterials(blueprint));
    }

    if (requestType === "blueprint-review") {
      return res.json({
        type: "blueprint-review",
        suggestions: ["Add room labels.", "Add exits.", "Verify device spacing.", "Add legend."],
        notes: ["Blueprint review generated by Sentinel Nexus AI."]
      });
    }

    if (requestType === "fire-code") {
      return res.json({
        type: "fire-code",
        notes: [
          "Review device spacing against adopted NFPA edition.",
          "Verify notification coverage with candela requirements.",
          "Confirm final design with AHJ."
        ]
      });
    }

    return res.json({
      type: requestType,
      message: "Sentinel Nexus AI route received request.",
      prompt
    });
  } catch (error) {
    return res.status(500).json({
      error: error instanceof Error ? error.message : "Sentinel Nexus AI failed."
    });
  }
});

app.post("/ai", (req, res) => {
  res.json({
    agent: req.body.agent || "sentinel",
    result: {
      message: "Use /gateway for the integrated Sentinel Nexus AI Builder."
    }
  });
});

app.post("/generate-building", (req, res) => {
  res.json(generateBlueprint(req.body.prompt || ""));
});

const port = process.env.PORT || 8787;

app.listen(port, () => {
  console.log(`Sentinel Nexus AI running on port ${port}`);
});
